theme: minima
title: Dan Carroll's Page Made with Jekyll
author: Dan Carroll
email: dcarroll809@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub is a great place to host your code projects.
  And Jekyll is pretty cool for configuring and creating static web pages.
  Going to see what this GitHub Learning Lab lesson does with a blog.

# social links
twitter_username: FloriDan Online # DO NOT include the @ character, or else the build will fail!
github_username:  dan-carroll # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
